### ISSUE TITLE
fgb_sage compile error for SageMath version 9.5.rc0

### ISSUE THREAD

**Issue by ypfmde** [mwageringel/fgb_sage#4]
The test `sage setup.py test` for SageMath version 9.5.rc0 (compiled from source without errors) on an up to date Manjaro Linux machine results in:

```
Compiling fgb_sage/_fgb_sage_modp.pyx because it changed.
[1/1] Cythonizing fgb_sage/_fgb_sage_modp.pyx

Error compiling Cython file:
------------------------------------------------------------
...
            e = self.monoms + j * self.n_variables
            mon = p_Init(_ring)
            IF PY_LIBMODE == 2:
                p_SetCoeff(mon, nlInit2gmp(self.coeffs[j], one, _ring.cf), _ring)
            ELSE:
                p_SetCoeff(mon, n_Init(self.coeffs[j], _ring), _ring)
                                                      ^
------------------------------------------------------------

fgb_sage/_fgb_sage_modp.pyx:219:55: Cannot assign type 'ring *' to 'n_Procs_s *'
Traceback (most recent call last):
  File "/home/mueller/Adm/local/fgb_sage/setup.py", line 135, in <module>
    ext_modules = [
  File "/home/mueller/Adm/local/fgb_sage/setup.py", line 136, in <listcomp>
    cythonize(
  File "/home/mueller/local/sage/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
    cythonize_one(*args)
  File "/home/mueller/local/sage/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: fgb_sage/_fgb_sage_modp.pyx
```

-- Peter Mueller (Wuerzburg)

**Comment by mwageringel** [comment]
Thank you for noticing this error so quickly and reporting it here. It should be fixed now. About the compilation warnings, on the other hand, I cannot do anything, but they can be ignored.

**Comment by ypfmde** [comment]
Thanks, it now works on two machines under the setup as described in the post.
